### ISSUE TITLE
Query __args that are Integer value are not converting into integer

### ISSUE THREAD

**Issue by BhupenT** [trayio/graphql-query-to-json#8]
Scenarios: lets say we got query like this:

> {
>   users (first: 1000, where: {showInFrontend: true}) {  // first : 1000 is an integer value
>     edges {
>         node {
>             databaseId
>         }
>     }
>   }
> }

the resulting argument object becomes:
`args { first: '1000', where: { showInFrontend: true } } // this is incorrect as its meant to be IntValue 
`

I did a modification to your code locally for now to fix it. The Fix:
In your getArguments and getArgumentObject function you also want to check the kind for IntValue like this eg in your getArguments function :
`} else if (arg.value.kind === 'IntValue') {  argsObj[arg.name.value] = parseInt(arg.value.value); {`

I can do a PR if you want. Also thanks saved me hours of work trying to convert to Json 👍

**Comment by rickschubert** [comment]
This is a great suggestion, thank you for this @BhupenT ! Could you open a pull request for it with an added unit test?

Do you know how the behaviour would be for other types, let's say floats - could you implement these number types as well? Would booleans work already? 

Thank you!

**Comment by thomaschaplin** [comment]
Thanks for raising this issue @BhupenT 👍🏼 

I agree with @rickschubert here! If you could raise a PR, that'd be great along with unit test coverage for your changes.

Great question @rickschubert, what will happen with floats and booleans etc

**Comment by BhupenT** [comment]
Sure thanks @rickschubert, I will do a PR sometime by tomorrow. Boolean works fine as selectionSet value must be true or false without quote. Haven’t tested with floats. We do need to support all the AST kinds if DocumentNode of that value is set as string type. Eg. value: ‘123.45’

**Comment by thomaschaplin** [comment]
@BhupenT I was wondering if you were still happy to take on this issue? We'd love to see a solution for it 🙏🏼 Let us know if there's anything we can do to assist 🤝

**Comment by thomaschaplin** [comment]
Hey @BhupenT, it's been a while since we heard from you.

Are you still interested in providing a PR to fix this issue? 
We would love to support you in getting this fixed, if not - don't worry we can look into it 👍🏼

**Comment by BhupenT** [comment]
Hi @thomaschaplin and @rickschubert. Thanks a lot guys. Sorry that i am late to the party, been busy and had to quickly do things on some project which had to work on so din't had time. I also found few other features that may be a good idea to add here. I just forked and put it there which i can create a PR if this is something that may interest you guys. 

- Support for inline fragments ( using __on similar to how [Json to gqlQuery](https://www.npmjs.com/package/json-to-graphql-query) does )
- Support for alias based query (using __aliasFor similar to [Json to gqlQuery](https://www.npmjs.com/package/json-to-graphql-query) does
So it can be used with the combination for JSON->Query and Query->Json

[Here](https://github.com/BhupenT/graphql-query-to-json) is the forked one which i just added a commit that i had implemented ages ago which i think its good to share it with you guys. [Commit changes view here ](https://github.com/BhupenT/graphql-query-to-json/commit/50052883593289e6ab32bf9263c3e927be73eff9)

Once again Thanks you all.

**Comment by thomaschaplin** [comment]
> Hi @thomaschaplin and @rickschubert. Thanks a lot guys. Sorry that i am late to the party, been busy and had to quickly do things on some project which had to work on so din't had time. I also found few other features that may be a good idea to add here. I just forked and put it there which i can create a PR if this is something that may interest you guys.
> 
> * Support for inline fragments ( using __on similar to how [Json to gqlQuery](https://www.npmjs.com/package/json-to-graphql-query) does )
> * Support for alias based query (using __aliasFor similar to [Json to gqlQuery](https://www.npmjs.com/package/json-to-graphql-query) does
>   So it can be used with the combination for JSON->Query and Query->Json
> 
> [Here](https://github.com/BhupenT/graphql-query-to-json) is the forked one which i just added a commit that i had implemented ages ago which i think its good to share it with you guys. [Commit changes view here ](https://github.com/BhupenT/graphql-query-to-json/commit/50052883593289e6ab32bf9263c3e927be73eff9)
> 
> Once again Thank you all.

Thanks @BhupenT - I've created an issue for this to be looked into. We may get in touch to discuss it with you further.

Thanks again

**Comment by harmeetsingh17** [comment]
@BhupenT @thomaschaplin Hi, just checking if we are currently supporting inline fragments query to be converted to json? if not, can you please suggest how we can convert it using any other method?

**Comment by VincentSC** [comment]
@harmeetsingh17 Checked this open PR if it does what you need? https://github.com/trayio/graphql-query-to-json/pull/23
